import type { Metadata } from 'next';
import { Poppins, Inter } from 'next/font/google';
import './globals.css';

const poppins = Poppins({
	variable: '--font-heading',
	subsets: ['latin'],
	weight: '100',
});

const inter = Inter({
	variable: '--font-body',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`font-[--font-body] ${poppins.variable} ${inter.variable} antialiased`}>
				{children}
			</body>
		</html>
	);
}
